name: Back-end tests
on: 
  push:
    branches: [main]

  pull_request:
    branches: ['*'] 

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Source Files
        uses: actions/checkout@v2

      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: 14
        
      - name: Install Dependencies
        run: cd app/backend && npm install

      - name: Lint Source Files
        run: cd app/backend && npm run lint

  test:
    name: Tests
    needs: lint
    runs-on: ubuntu-20.04
    env:
      DB_HOST: localhost

    steps:
      - name: Checkout Source Files
        uses: actions/checkout@v2

      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: 14
          
      - name: Builds Docker containers
        run: npm run compose:up

      - name: Run Tests and coverage
        run: docker exec app_backend_1 sh -c "npm test && npm run test:coverage"

      - name: Print Test Report
        run: docker exec app_backend_1 sh -c "npm run test:report"

      - name: Copy report from container to local env
        run: sudo docker cp app_backend_1:app/.nyc_coverage/lcov.info /trybe-futebol-clube && cd ../ && ls -la

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
