name: Back-end tests
on: 
  push:
    branches: [main]

  pull_request:
    branches: ['*'] 

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Source Files
        uses: actions/checkout@v2

      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: 14
        
      - name: Install Dependencies
        run: cd app/backend && npm install

      - name: Lint Source Files
        run: cd app/backend && npm run lint

  test:
    name: Tests
    needs: lint
    runs-on: ubuntu-20.04
    env:
      DB_HOST: localhost

    steps:
      - name: Checkout Source Files
        uses: actions/checkout@v2

      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: 14
          
      - name: Run Docker-compose and test
        run: npm test
